name: XPVault
version: 1.3
main: com.falafel77.XPVault.XPVault
api-version: 1.13
commands:
  savexp:
    description: Saves a specified amount of a player's XP.
    usage: /savexp <amount>
    aliases: [sxp]
  givexp:
    description: Gives XP to a player.
    usage: /givexp <player> <amount>
    aliases: [gxp]
  retrievexp:
    description: Retrieves saved XP for a player. Optionally specify an amount.
    usage: /retrievexp [amount]
    aliases: [rxp]



  adminxp:
    description: Admin commands for managing saved XP.
    usage: /adminxp <resetall|set|add|remove> [player] [amount]
    permission: xpvault.admin
    permission-message: You do not have permission to use this command.




  checkxp:
    description: Checks your current XP and stored XP.
    usage: /checkxp
    aliases: [cxp]

