# XPVault Configuration

# =========================
# Worlds where XPVault is enabled
# =========================
enabled-worlds:
  - world
  - world_nether
  - world_the_end

# =========================
# Cooldown settings for each command
# =========================
cooldowns:
  savexp:
    enabled: true      # Enable/disable cooldown for /savexp
    seconds: 10        # Cooldown duration in seconds
  givexp:
    enabled: true      # Enable/disable cooldown for /givexp
    seconds: 15        # Cooldown duration in seconds
  retrievexp:
    enabled: true     # Enable/disable cooldown for /retrievexp
    seconds: 5         # Cooldown duration in seconds
  checkxp:
    enabled: false     # Enable/disable cooldown for /checkxp
    seconds: 0         # Cooldown duration in seconds